name: SFDX Test Run on Push
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v4.1.1
        
      - name: 'Validating Source to org'
        run: |
            # following usage for Demo only, "SFDX version" | "Displaying Org details"
            echo "SFDX version"
            echo "-------------------------"
            sfdx -v
            echo "Displaying Org details..."
            echo "-------------------------"
            sfdx force:org:display

            # echo "Validating source to target org..."
            # echo "-------------------------"
            sfdx force:source:deploy -p force-app/main/default -c
